### ISSUE TITLE
Error: ImportError: cannot import name wave2

### ISSUE THREAD

**Issue by bijookha** [milanboers/pytune#1]
python chordfinder.py 
Traceback (most recent call last):
  File "chordfinder.py", line 27, in <module>
    from pytune import wave2, freqset, noteset, scalefinder, functions
ImportError: cannot import name wave2

Are there circular imports? Can you please fix this? Nice program by the way, did you make any more progress? Would love an update. Thanks for creating this.

**Comment by milanboers** [comment]
Make sure you compile the pyx files in the pytune module folder. These are cython files.

**Comment by bijookha** [comment]
Thanks
